apiVersion: agsh/v1
kind: ProjectSpec

meta:
  name: "repo-health-check"
  description: "Analyze a GitHub repo and produce a health report with recommendations"
  author: "demo"
  created: "2025-02-09"
  tags: ["demo", "agent", "autonomy", "github", "analysis"]

goal: |
  Perform a health check on a given GitHub repository. Analyze its
  recent activity, open issues, PR velocity, and staleness indicators.
  Produce a health report with a score and actionable recommendations.

  The agent should:
  1. Discover what commands are available
  2. Gather data from multiple sources (repo info, PRs, issues)
  3. Analyze the data and compute health metrics
  4. Write a structured report
  5. Verify the report meets quality standards

constraints:
  - "Read-only access to GitHub"
  - "Must handle API failures gracefully (retry or skip with note)"
  - "Report must be factual — no invented data"
  - "Complete within 120 seconds"

guidelines:
  - "Health score should be 0-100 based on defined metrics"
  - "Metrics to consider: days since last commit, open PR age, issue response time, bus factor"
  - "Each recommendation should be specific and actionable"
  - "Include a summary section at the top"
  - "Use emoji indicators: healthy, warning, critical"

success_criteria:
  - type: "not_empty"
    target: "output"
    message: "Report must not be empty"
  - type: "contains"
    target: "output"
    expected: "Health Score"
    message: "Report must include a health score"
  - type: "contains"
    target: "output"
    expected: "Recommendation"
    message: "Report must include recommendations"
  - type: "llm_judge"
    target: "output"
    expected: "A structured health report with a numeric score, multiple metrics with status indicators, and specific actionable recommendations"
    message: "Report must be comprehensive and well-structured"

allowed_commands:
  - "github:*"
  - "fs:write"
  - "http:get"

output:
  path: "./reports/health-report.md"
  format: "markdown"

params:
  - name: "repo"
    type: "string"
    default: "golang/go"
    description: "GitHub repo in owner/name format"
  - name: "lookback_days"
    type: "integer"
    default: 30
    description: "Days of history to analyze"
