apiVersion: agsh/v1
kind: ProjectSpec

meta:
  name: "github-weekly-report"
  description: "Weekly summary of GitHub activity across owned repos"
  author: "demo"
  created: "2025-02-09"
  tags: ["demo", "github", "platform", "reporting"]

goal: |
  Generate a markdown report summarizing GitHub activity for the
  authenticated user's repositories over the past N days. Include
  PRs (opened, merged, closed), issues (opened, closed), and
  notable commits.

constraints:
  - "Only include repos owned by the authenticated user"
  - "Do not create, modify, or delete any GitHub resources (read-only)"
  - "Output must be a single markdown file"
  - "Must complete within 60 seconds"
  - "Respect GitHub API rate limits"

guidelines:
  - "Group activity by repository"
  - "Within each repo, group by type: PRs, Issues, Commits"
  - "Keep descriptions to 1-2 sentences per item"
  - "Include direct links to GitHub"
  - "Flag PRs that have been open longer than 7 days"
  - "If a repo had no activity, omit it from the report"

success_criteria:
  - type: "not_empty"
    target: "output"
    message: "Report must not be empty"
  - type: "contains"
    target: "output"
    expected: "## "
    message: "Report must contain markdown section headers"
  - type: "contains"
    target: "output"
    expected: "github.com"
    message: "Report must contain GitHub links"

allowed_commands:
  - "github:repo:info"
  - "github:pr:list"
  - "fs:write"

output:
  path: "./reports/weekly-{{date}}.md"
  format: "markdown"

params:
  - name: "date_range_days"
    type: "integer"
    default: 7
    description: "How many days back to look"
  - name: "include_forks"
    type: "boolean"
    default: false
    description: "Include forked repos in the report"
